script:
  - npm test --single-run
  - node_modules/.bin/protractor test/e2e/conf.js --browser=firefox
language: node_js
node_js:
  - "5.5.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install: npm install
before_script:
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - webdriver-manager update
  - webdriver-manager start > /dev/null &
  - npm start > /dev/null &
  - sleep 3
